# Problem 3.1

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('cereal.csv', sep=';')

In [3]:
df.head()

,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
0,String,Categorical,Categorical,Int,Int,Int,Int,Float,Float,Int,Int,Int,Int,Float,Float,Float
1,100% Bran,N,C,70,4,1,130,10,5,6,280,25,3,1,0.33,68.402973
2,100% Natural Bran,Q,C,120,3,5,15,2,8,8,135,0,3,1,1,33.983679
3,All-Bran,K,C,70,4,1,260,9,7,5,320,25,3,1,0.33,59.425505
4,All-Bran with Extra Fiber,K,C,50,4,0,140,14,8,0,330,25,3,1,0.5,93.704912

In [4]:
df.drop(df.index[0], inplace = True)

In [5]:
df.head()

,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
1,100% Bran,N,C,70,4,1,130,10,5,6,280,25,3,1,0.33,68.402973
2,100% Natural Bran,Q,C,120,3,5,15,2,8,8,135,0,3,1,1,33.983679
3,All-Bran,K,C,70,4,1,260,9,7,5,320,25,3,1,0.33,59.425505
4,All-Bran with Extra Fiber,K,C,50,4,0,140,14,8,0,330,25,3,1,0.5,93.704912
5,Almond Delight,R,C,110,2,2,200,1,14,8,-1,25,3,1,0.75,34.384843

In [6]:
X = df[['name', 'mfr', 'type', 'calories', 'protein', 'fat', 'sodium', 'fiber', 'carbo', 'sugars', 'potass', 'vitamins', 'shelf', 'weight', 'cups']]
y = df['rating']

In [7]:
X

,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups
1,100% Bran,N,C,70,4,1,130,10,5,6,280,25,3,1,0.33
2,100% Natural Bran,Q,C,120,3,5,15,2,8,8,135,0,3,1,1
3,All-Bran,K,C,70,4,1,260,9,7,5,320,25,3,1,0.33
4,All-Bran with Extra Fiber,K,C,50,4,0,140,14,8,0,330,25,3,1,0.5
5,Almond Delight,R,C,110,2,2,200,1,14,8,-1,25,3,1,0.75
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73,Triples,G,C,110,2,1,250,0,21,3,60,25,3,1,0.75
74,Trix,G,C,110,1,1,140,0,13,12,25,25,2,1,1
75,Wheat Chex,R,C,100,3,1,230,3,17,3,115,25,1,1,0.67
76,Wheaties,G,C,100,3,1,200,3,17,3,110,25,1,1,1
77,Wheaties Honey Gold,G,C,110,2,1,200,1,16,8,60,25,1,1,0.75

In [8]:
y

1     68.402973
2     33.983679
3     59.425505
4     93.704912
5     34.384843
        ...
73    39.106174
74    27.753301
75    49.787445
76    51.592193
77    36.187559
Name: rating, Length: 77, dtype: object

In [9]:
X = X.join(pd.get_dummies(X['name']))
X = X.join(pd.get_dummies(X['mfr']))
X = X.join(pd.get_dummies(X['type']))

In [10]:
X = X.drop(['name', 'mfr', 'type'], axis=1)

In [11]:
X

,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,...,Wheaties Honey Gold,A,G,K,N,P,Q,R,C,H
1,70,4,1,130,10,5,6,280,25,3,...,0,0,0,0,1,0,0,0,1,0
2,120,3,5,15,2,8,8,135,0,3,...,0,0,0,0,0,0,1,0,1,0
3,70,4,1,260,9,7,5,320,25,3,...,0,0,0,1,0,0,0,0,1,0
4,50,4,0,140,14,8,0,330,25,3,...,0,0,0,1,0,0,0,0,1,0
5,110,2,2,200,1,14,8,-1,25,3,...,0,0,0,0,0,0,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73,110,2,1,250,0,21,3,60,25,3,...,0,0,1,0,0,0,0,0,1,0
74,110,1,1,140,0,13,12,25,25,2,...,0,0,1,0,0,0,0,0,1,0
75,100,3,1,230,3,17,3,115,25,1,...,0,0,0,0,0,0,0,1,1,0
76,100,3,1,200,3,17,3,110,25,1,...,0,0,1,0,0,0,0,0,1,0
77,110,2,1,200,1,16,8,60,25,1,...,1,0,1,0,0,0,0,0,1,0

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 15)

In [13]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [14]:
print("Intercept: ", model.intercept_)
print("Coefficients:")
list(zip(X, model.coef_))

Intercept:  55.585937033368324
Coefficients:

[('calories', -0.22511080038744324),
 ('protein', 3.1809900925548287),
 ('fat', -1.6354983135869385),
 ('sodium', -0.05420778872230958),
 ('fiber', 3.247873942706498),
 ('carbo', 1.0720789723537818),
 ('sugars', -0.7498618908030438),
 ('potass', -0.02868764785417177),
 ('vitamins', -0.04988522280079044),
 ('shelf', -0.015748797728137337),
 ('weight', 0.12098707755231251),
 ('cups', -0.05235776523498087),
 ('100% Bran', 0.23933274425040782),
 ('100% Natural Bran', -0.23926090170478512),
 ('All-Bran', -0.1475863736306319),
 ('All-Bran with Extra Fiber', 2.886579864025407e-15),
 ('Almond Delight', 0.1765232350850218),
 ('Apple Cinnamon Cheerios', 0.0029282680808507162),
 ('Apple Jacks', 0.15721073261444304),
 ('Basic 4', 0.16735709482020653),
 ('Bran Chex', 0.03775174462052988),
 ('Bran Flakes', -2.3314683517128287e-15),
 ("Cap'n'Crunch", -0.05559986450720665),
 ('Cheerios', 0.18632190594900247),
 ('Cinnamon Toast Crunch', -0.24890046648786365),
 ('Clusters', 0.013049381030309493),
 ('Cocoa Puffs', -0.11287330378847876),
 ('Corn Chex', -0.04827089438286243),
 ('Corn Flakes', -0.05182510371080318),
 ('Corn Pops', 0.1188670150322038),
 ('Count Chocula', 3.7192471324942744e-15),
 ("Cracklin' Oat Bran", -0.2311015435801804),
 ('Cream of Wheat (Quick)', 1.6653345369377348e-16),
 ('Crispix', 0.07497893658980413),
 ('Crispy Wheat & Raisins', -0.07943106763822505),
 ('Double Chex', -0.1558483688224959),
 ('Froot Loops', 0.07633515539832222),
 ('Frosted Flakes', 1.6653345369377348e-16),
 ('Frosted Mini-Wheats', 0.15683180454508874),
 ('Fruit & Fibre Dates, Walnuts, and Oats', -0.022203051364211423),
 ('Fruitful Bran', 0.1437345337801769),
 ('Fruity Pebbles', -0.1279431605898452),
 ('Golden Crisp', 5.551115123125783e-17),
 ('Golden Grahams', -0.1401478316826428),
 ('Grape Nuts Flakes', 0.18814076404782595),
 ('Grape-Nuts', 0.19066523686373368),
 ('Great Grains Pecan', -0.03151986714100212),
 ('Honey Graham Ohs', 0.07507122183422409),
 ('Honey Nut Cheerios', 5.551115123125783e-17),
 ('Honey-comb', -0.12788766018023914),
 ('Just Right Crunchy  Nuggets', -0.2319504784300991),
 ('Just Right Fruit & Nut', 0.02836936360143937),
 ('Kix', -0.00403779296869099),
 ('Life', 0.11204265931847181),
 ('Lucky Charms', -0.04565628714653891),
 ('Maypo', -2.7755575615628914e-17),
 ('Muesli Raisins, Dates, & Almonds', 0.043032629878326914),
 ('Muesli Raisins, Peaches, & Pecans', -5.551115123125783e-17),
 ('Mueslix Crispy Blend', -2.7755575615628914e-17),
 ('Multi-Grain Cheerios', 0.020159987746304914),
 ('Nut&Honey Crunch', 0.0),
 ('Nutri-Grain Almond-Raisin', 0.03024614792864504),
 ('Nutri-grain Wheat', 0.120462412266147),
 ('Oatmeal Raisin Crisp', -0.07031484354150472),
 ('Post Nat. Raisin Bran', -0.0306103181545589),
 ('Product 19', 0.0),
 ('Puffed Rice', -0.09877844899021604),
 ('Puffed Wheat', -0.05780489229448976),
 ('Quaker Oat Squares', 0.1402322656399296),
 ('Quaker Oatmeal', -0.039293582144626096),
 ('Raisin Bran', -0.18047359810148197),
 ('Raisin Nut Bran', 0.0),
 ('Raisin Squares', 0.0),
 ('Rice Chex', 0.0),
 ('Rice Krispies', -0.1782252386821432),
 ('Shredded Wheat', -0.08429586862275765),
 ("Shredded Wheat 'n'Bran", 0.011873470656448063),
 ('Shredded Wheat spoon size', -0.057246516075194376),
 ('Smacks', 0.03504753921808841),
 ('Special K', 0.1748649162606668),
 ('Strawberry Fruit Wheats', 0.028298717748075925),
 ('Total Corn Flakes', -0.07034973040827058),
 ('Total Raisin Bran', 0.0),
 ('Total Whole Grain', 0.0849967958743802),
 ('Triples', -0.13082224930633615),
 ('Trix', 0.053099848536993205),
 ('Wheat Chex', -0.031450835343023426),
 ('Wheaties', 0.17337751800555545),
 ('Wheaties Honey Gold', 0.0705060921997802),
 ('A', 0.0),
 ('G', -0.13073668072516598),
 ('K', 0.09578622109968438),
 ('N', 0.13796254795697704),
 ('P', 0.038641943481702384),
 ('Q', -0.16339154284869828),
 ('R', 0.021737511035501145),
 ('C', 0.039293582144626055),
 ('H', -0.039293582144626096)]

In [15]:
y_pred = model.predict(X_test)
y_pred

array([55.09237796, 35.28488951, 53.33119939, 55.54557608, 42.15230747,
       39.8280766 , 22.56244283, 31.40840809, 31.02688194, 34.11240199,
       30.32685419, 30.12692367, 92.98072118, 41.58819889, 64.20722487,
       28.65678304])

In [16]:
from sklearn import metrics
mae = metrics.mean_absolute_error(y_test, y_pred)
mse = metrics.mean_squared_error(y_test, y_pred)
rmse = np.sqrt(metrics.mean_squared_error(y_test, y_pred))
print('Mean Absolute Error:', mae)
print('Mean Square Error:', mse)
print('Root Mean Square Error:', rmse)

Mean Absolute Error: 0.15397197108209615
Mean Square Error: 0.05366080578902759
Root Mean Square Error: 0.23164802133631013

In [17]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.9998221035745308

In [18]:
model.score(X, y)

0.9999427495952645

In [19]:
list(y_test)
y_test = y_test.map(lambda x: float(x))

In [20]:
y_test.dtype

dtype('float64')

In [21]:
y_pred.dtype

dtype('float64')

# Problem 3.4

In [22]:
def r_squared(y_test, y_pred):
    y_bar = np.mean(y_test)
    ss_total = np.sum((y_test - y_bar) ** 2)
    sse = np.sum((y_pred - y_bar) ** 2)
    ssr = np.sum((y_test - y_pred) ** 2)
    scikit_r2 = r2_score(y_test, y_pred)
    r2score = 1 - (ssr/ss_total) 
    print('Calculated R Squared: ', r2score)
    print('Scikit R Squared: ', scikit_r2)

# Problem 3.5

In [23]:
r_squared(y_test, y_pred)

Calculated R Squared:  0.9998221035745308
Scikit R Squared:  0.9998221035745308